### PR TITLE
Career qs

### LINKED ISSUE #56: We have an overflow in smaller screens
image

Only happens on Firefox.

### PR DESCRIPTION
**Pull request by marimeireles**
The CSS code is really ugly but that was the better/quickier way I found to fix it.
Instead of changing the minified file I could have changed the less file (I think it has variables, it's uncompiled CSS stuff? not sure) the point is that we don't have it cause we just have ctrlc/ctrlv of the compiled files.

This PR is a WIP because we still need the text for the jobs.

Fixes #56

### CODE REVIEW

**Comment by marimeireles** [comment]
@SylvainCorlay: https://docs.google.com/document/d/1OQ2DbkBhJew2Y---YaQ9MlSbYZOmFkV5OfrKp4dOCKs/edit?usp=sharing

**Comment by marimeireles** [comment]
Hey @SylvainCorlay, do you like this unordered list or should I transform this in one unique paragraph?
(It looks weird if it's one paragraph for each paragraph in the doc)
image

**Comment by marimeireles** [comment]
The weird CSS around it is just a bug of the screensaver!

**Comment by marimeireles** [comment]
Seems good.

**Comment by SylvainCorlay** [comment]
Removed the navbarlink temporarily and merging.

**Pull request merged**
