### PR TITLE
Update organisation -> organization

### PR DESCRIPTION
**Pull request by jtpio**
Part of #145

### CODE REVIEW

**Review by arjxn-py — COMMENTED** [review]
Hi @jtpio, Thanks.
There are some more similar instances, listing them here just for further reference: 

- https://github.com/QuantStack/quantstack.github.io/blob/105659de92f2a68af53bab6546af65c79bbe2ec7/src/components/home/ProjectsOverview/SupplyChainReversed.tsx#L25
- https://github.com/QuantStack/quantstack.github.io/blob/105659de92f2a68af53bab6546af65c79bbe2ec7/src/components/home/ProjectsOverview/descriptions/Computing.md?plain=1#L1
- https://github.com/QuantStack/quantstack.github.io/blob/105659de92f2a68af53bab6546af65c79bbe2ec7/src/components/services/descriptions/Support.md?plain=1#L1

**Comment by jtpio** [comment]
Thanks @arjxn-py :+1: 

I pushed a new commit to fix other occurrences for that word, but maybe we could run a spell checker on the whole repo to find other typos more easily.

**Comment by arjxn-py** [comment]
Would a pre-commit hook like [codespell-project/codespell](https://github.com/codespell-project/codespell) help?

**Comment by jtpio** [comment]
Something like that yes. A hook could be useful, but a one-shot pass could be a good starting point too.

**Comment by arjxn-py** [comment]
> Something like that yes. A hook could be useful, but a one-shot pass could be a good starting point too.

Thanks for validating :)
As far as I recall, first pre-commit run should be able to do a one shot pass.
In my opinion it should be worth trying on a PR and see if it's effective and feasible. 
I'd be more than happy to assist for the same. I could try opening one and iterate over it :)

**Comment by jtpio** [comment]
> I'd be more than happy to assist for the same. I could try opening one and iterate over it :)

Sure, feel free to open a PR, thanks!

**Comment by SylvainCorlay** [comment]
LGTM.

**Pull request merged**
