### PR TITLE
add Matthias profile

### PR DESCRIPTION
**Pull request by MMesch**
My profile is in this PR @SylvainCorlay . My name seems to be too long for the default layout though.

https://github.com/user-attachments/assets/189bf90d-2a3d-4178-bbd0-fb931bd75dd7

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Ping @HaudinFlorence as this may require changing a bit the default layout.

**Comment by HaudinFlorence** [comment]
Hello.@MMesch @SylvainCorlay I will try to made the relevant changes to have your name on one line

**Comment by SylvainCorlay** [comment]
Thanks. I let you do it in a follow up PR.

**Comment by HaudinFlorence** [comment]
After checking, it seems that it is ok on the master branch and on the deployed version 
Screenshot from 2024-09-02 17-44-51

**Pull request merged**
