### PR TITLE
Michael just added his profile

### PR DESCRIPTION
**Pull request by MichaelKora**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@MichaelKora thanks! It seems that your git author email corresponds to the @istmikora account and not your current github account.

**Comment by MichaelKora** [comment]
@SylvainCorlay oh really? i'll update my email address then

**Comment by MichaelKora** [comment]
@SylvainCorlay thanks for the notification. i already updated it and my next push should show my right/current accout

**Comment by SylvainCorlay** [comment]
Do you want to fix this commit or are you fine as it is?

**Comment by SylvainCorlay** [comment]
The better practice is to create a PR from a feature branch.

Here is a way to do so from where you are:

```bash
git remote add upstream https://github.com/QuantStack/quantstack.github.io.git  # adding the upstream remote
git fetch upstream                                         # synchronizing the upstream repo
git reset upstream/master                                  # reseting your master branch while keeping changes locally
git checkout -b michael-profile                            # working from a new branch
git add img/ michael.html the-team.html                    # staging files for commit
git commit -m "Michael just added his profile"             # commit your changes
git push origin michael-profile                            # push to your fork 
```

then open a PR from michael-profile branch.

**Comment by SylvainCorlay** [comment]
Closing as superseded by #79.

**Pull request closed without merging**
